# -*- coding: utf-8 -*-
"""SVM&naive_bayes.ipynb

Automatically generated by Colaboratory.

"""

import pandas as pd
df = pd.read_table('https://raw.githubusercontent.com/arib168/data/main/spam.tsv')
df.info()

df

x = df['message'].values
y= df['label'].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)
y_test.shape

from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')
x_train_vect = vect.fit_transform(x_train)
x_test_vect = vect.transform(x_test)

"""by svc() method"""

from sklearn.svm import SVC
model = SVC()
model.fit(x_train_vect,y_train)

y_pred = model.predict(x_test_vect)
y_pred

y_test

"""compring of y_pred & y_test

"""

from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

"""fromm pipeline method

"""

from sklearn.pipeline import make_pipeline
model1  = make_pipeline(CountVectorizer(),SVC())
model1.fit(x_train,y_train)
y_pred1 = model1.predict(x_test)

y_pred1

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred1,y_test)

"""using naive bayes classification

"""

from sklearn.naive_bayes import MultinomialNB
model3 = MultinomialNB()
model3.fit(x_train_vect,y_train)
y_pred3 = model.predict(x_test_vect)
y_pred3

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_pred3,y_test)

len(y_pred1)

"""multinomial with pipeline"""

from sklearn.pipeline import make_pipeline
model4 = make_pipeline(CountVectorizer(),MultinomialNB())
model4.fit(x_train,y_train)

y_pred4 = model4.predict(x_test)
y_pred4

from sklearn.metrics import accuracy_score
accuracy_score(y_pred4,y_test)

"""model persuistance

"""

import joblib
joblib.dump(model4,'spam-ham')#serialisation
text_model = joblib.load('spam-ham')#de-serialiastion
text_model.predict(['free tickets mon key'])

"""creating web app using stream lit for spam ham

"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# st.title("SPAM-HAM CLASSIFIER")
# text_model = joblib.load('/content/spam-ham')
# ip = st.text_input("enter a MESSAGE : ")
# op = text_model.predict([ip])
# if st.button('PREDICT'):
#   st.title(op[0])
#

!streamlit run app.py &npx localtunnel --port 8501

!pip install streamlit
